### ISSUE TITLE
Filter field not working as expected

### ISSUE THREAD

**Issue by rvaneeuwijk** [WLBQE/homebridge-august-door-sense#3]
Hi. Looks like a really promising plugin for my purposes. I have a Yale account with 3 homes and Yale locks in each of these homes:

- Home 1 in Sweden has a door with a Yale Linus lock called Front Door (ID: 3B7BBCB3D1836401A5C9800781F47572)
- Home 2 in Sweden has two doors with Yale Linus locks called Studio Door (ID: D1C513EF7B21EB6B067708447F6F8C4B) and Bedroom Door (ID: 4D8A48516369D1DF526857B043716840)
- Home 3 in Canada has three doors with Yale Assure locks Front Door (ID: 4E785D6ED0214395A2BF3C1B73EA1CDA), Back Door (ID: 5C9FD22F48894B5188C77B48014267BD), and Garage Door (ID: 0A62274254E24257A87DCA1972F5D22B).

I installed the August Door Sense plugin on HOOBS and created an August Door Sense bridge that I added as an accessory in Home 3. I therefore excluded the three door sensors in Homes 1 and 2 in the configuration of the plugin. Here's the configuration:

    "platform": "AugustDoorSense",
    "name": "August DoorSense",
    "email": "MYEMAIL",
    "password": "MYPASSWORD",
    "installId": "MYINSTALLID",
    "filter": "3B7BBCB3D1836401A5C9800781F47572,4D8A48516369D1DF526857B043716840,D1C513EF7B21EB6B067708447F6F8C4B",
    "code": "MYCODE"

However, after restarting the bridge, all 6 door sensors appear in Home 3 in both HOOBS and Apple Home. The "filter" field in the plugin configuration does not seem to be working as expected.

In addition, while the Garage Door and Back Door sensors in Home 3 are responding correctly, the Front Door sensor in Home 3 is non-responsive: it shows the door is closed, whether the door is actually closed or open. May this have to do with the fact that there is a second door called Front Door in Home 1, which is failing to get excluded? That door sensor, by the way, is showing up as unresponsive in Apple Home but as closed on HOOBS. But all the sensors are working fine in the Yale app.

Finally, I am getting errors in the log on HOOBS that may shed light on the above two issues. Here is the log since the last restart of the August Door Sense bridge on HOOBS:

1/2/2023, 11:36:01 AMAugust Door Sense Bridge starting
1/2/2023, 11:36:11 AMAugust Door Sense BridgeLoaded plugin 'homebridge-august-door-sense'
1/2/2023, 11:36:11 AMAugust Door Sense BridgeLoading 1 platforms...
1/2/2023, 11:36:11 AMAugust Door Sense BridgeBridge is running on port 51886.
1/2/2023, 11:36:12 AMAugust Door Sense BridgeAugust DoorSenseERRORError parsing JSON: {"Email":"MYEMAIL","PhoneNo":"MYPHONE","UserID":"MYUSERID","FirstName":"MYFIRSTNAME","LastName":"MYLASTNAME","imageInfo":{"original":{"width":1242,"height":1359,"format":"webp","url":"https://d33mytkkohwnk6.cloudfront.net/user/3ab79e11-7349-41ce-9b66-6bc72f047e75/b6d5a2b0-0349-4c61-8a4d-9fd85daab7a7.webp","secure_url":"https://d33mytkkohwnk6.cloudfront.net/user/3ab79e11-7349-41ce-9b66-6bc72f047e75/b6d5a2b0-0349-4c61-8a4d-9fd85daab7a7.webp"},"thumbnail":{"width":128,"height":128,"format":"webp","url":"https://d33mytkkohwnk6.cloudfront.net/user/3ab79e11-7349-41ce-9b66-6bc72f047e75/e9033149-b991-45f4-9eaf-4d2a7a03c2a3.webp","secure_url":"https://d33mytkkohwnk6.cloudfront.net/user/3ab79e11-7349-41ce-9b66-6bc72f047e75/e9033149-b991-45f4-9eaf-4d2a7a03c2a3.webp"}},"locale":{"lang
1/2/2023, 11:36:12 AMAugust Door Sense BridgeAugust DoorSenseERRORError parsing JSON: uage":"en","country":"CA"},"optedInToOrchestra":false,"tokens":[{"type":"subscription-management","token":"server-removed"}]}
1/2/2023, 11:36:13 AMAugust Door Sense BridgeAugust DoorSense[{"id":"0A62274254E24257A87DCA1972F5D22B","name":"Garage Door","macAddress":"78:9C:85:1A:2F:CA","houseId":"37264e0f-c4cc-4749-ab2c-308aa17908c5","houseName":"Castle on the Prairie"},{"id":"3B7BBCB3D1836401A5C9800781F47572","name":"Front Door","macAddress":"78:9C:85:0F:52:F9","houseId":"4b0a16c7-8c42-472f-b72c-89826da4c196","houseName":"Little Island Hus"},{"id":"4D8A48516369D1DF526857B043716840","name":"Bedroom Door","macAddress":"78:9C:85:0F:6B:0D","houseId":"7fb681bc-6a37-4b71-b345-987ced2d4617","houseName":"Little Island Brygghus"},{"id":"4E785D6ED0214395A2BF3C1B73EA1CDA","name":"Front Door","macAddress":"78:9C:85:1A:41:B9","houseId":"37264e0f-c4cc-4749-ab2c-308aa17908c5","houseName":"Castle on the Prairie"},{"id":"5C9FD22F48894B5188C77B48014267BD","name":"Back Door","macAddress":"78:9C:85:1C:32:85","houseId":"37264e0f-c4cc-4749-ab2c-308aa17908c5","houseName":"Castle on the Prairie"},{"id":"D1C513EF7B21EB6B067708447F6F8C4B","name":"Studio Door","macAddress":"78:9C:85:0F:9F:50","houseId":"7fb681bc-6a37-4b71-b345-987ced2d4617","houseName":"Little Island Brygghus"}]
1/2/2023, 11:36:13 AMAugust Door Sense BridgeAugust DoorSenseAdding new accessory: Garage Door
1/2/2023, 11:36:13 AMAugust Door Sense BridgeAugust DoorSenseAdding new accessory: Front Door
1/2/2023, 11:36:13 AMAugust Door Sense BridgeAugust DoorSenseAdding new accessory: Bedroom Door
1/2/2023, 11:36:13 AMAugust Door Sense BridgeAugust DoorSenseAdding new accessory: Front Door
1/2/2023, 11:36:13 AMAugust Door Sense BridgeAugust DoorSenseAdding new accessory: Back Door
1/2/2023, 11:36:13 AMAugust Door Sense BridgeAugust DoorSenseAdding new accessory: Studio Door
1/2/2023, 11:36:26 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
 Error: Unknown door status: kAugDoorState_Init
    at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
1/2/2023, 11:36:38 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
 Error: Unknown door status: kAugDoorState_Init
    at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
1/2/2023, 11:36:49 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
 Error: Unknown door status: kAugDoorState_Init
    at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
1/2/2023, 11:36:49 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
 Error: Unknown door status: kAugDoorState_Init
    at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
1/2/2023, 11:36:49 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
 Error: Unknown door status: kAugDoorState_Init
    at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
1/2/2023, 11:36:49 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
 Error: Unknown door status: kAugDoorState_Init
    at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
1/2/2023, 11:36:56 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
 Error: Unknown door status: kAugDoorState_Init
    at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
1/2/2023, 11:37:06 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
 Error: Unknown door status: kAugDoorState_Init
    at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

These errors recur every 10 seconds or so.

The environment I am running is:
Plugin Version: 2.3.1
Homebridge Version: 1.5.0
Node.js Version: 16.19.0
NPM Version: Unknown
Operating System: HOOBS

Please let me know if I can provide any additional information to help you identify the cause of the issue. Thank you very much in advance for looking into this.

**Comment by rvaneeuwijk** [comment]
Update: The issue with the unresponsive Front Door sensor in Home 3 was caused by an issue on my end and has now been resolved. The issue that the plug-in ignores the filter list (at least for locks that are not in the Apple Home on which the plug-in bridge is installed) remains.

**Comment by rvaneeuwijk** [comment]
Update: I have also noted the following error message appearing periodically in the HOOBS log:

1/5/2023, 11:27:58 AMAugust Door Sense BridgeAugust DoorSenseERRORError reaching August server: Error: write EPROTO 3069617200:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1558:SSL alert number 40

Any idea what that means?

**Comment by bwp91** [comment]
@rvaneeuwijk @WLBQE this original error, can it still be reproduced in the plugin? on the current version?

```
1/2/2023, 11:36:38 AMAugust Door Sense BridgeAugust DoorSenseERRORGetDoorStatus threw an error:
Error: Unknown door status: kAugDoorState_Init
at augustGetDoorStatus (/var/lib/hoobs/augustdoorsensebridge/node_modules/homebridge-august-door-sense/src/august.ts:254:13)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

also @rvaneeuwijk this error in your logs, does it crash the plugin? or does it _just_ show in the log?

```
1/5/2023, 11:27:58 AMAugust Door Sense BridgeAugust DoorSenseERRORError reaching August server: Error: write EPROTO 3069617200:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1558:SSL alert number 40
```

**Comment by rvaneeuwijk** [comment]
@bwp91: When I last checked (early April), it was still not working reliably with the same issues I reported before. I checked I was running the most recent version. Am currently travelling, but will have another look after I get to my destination by the end of this week. Thanks!
